### PR TITLE
fix showcase: use the Legacy Materia modules

### PR DESCRIPTION
**Pull request by JeanMeche**
For the v15 Migration, the demo showcase should rely on the legacy modules (non-MDC components). 

In this commit the v15 migration schematics was applied.

### CODE REVIEW

**Comment by MatthieuRiegler-eaton** [comment]
Hi, I'm not so sure which branch this should land in. Let me know, if I need to change something!

**Review by daileytj — APPROVED** [review]
Looks good. Thanks!

**Comment by daileytj** [comment]
@JeanMeche this looks good, but can you update the conflicting files that occurred after I updated the target branch?

**Comment by JeanMeche** [comment]
Yeah I forgot that branch, the changes are already on it. 

I'll close this one !

**Pull request closed without merging**
